  # Generating the Dockerfile for the project
 FROM python:3.13 as builder
 WORKDIR /app
 COPY . .
 RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*
 RUN pip install -r requirements.txt
 RUN pip install mysqlclient  

 #================================
 #stage 2 begains from here

 FROM python:3.13-slim
 RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

 COPY --from=builder /usr/local/lib/python3.13/site-packages/ /usr/local/lib/python3.13/site-packages/ 
 COPY . .
 CMD ["python", "app.py"]