services:
  mysql:
    image: mysql:latest
    container_name: sql-server
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: flask-db
    ports:
     - "3306:3306"
    volumes:
     - flask-data:/var/lib/mysql
      
    networks:
    - flask-tier
    healthcheck:
      test: [ "CMD","mysqladmin","ping", "-h", "localhost", "-uroot", "-padmin" ]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  phpmyadmin:
    image:
    container_name: sql-ui
    environment:
      PMA_HOST: sql-server
      PMA_PORTS: 3306
    ports:
      - "8080:80"
      
  flask-app:
    build:
      context: .
    container_name: flask-app
    environment:
      MYSQL_HOST: sql-server
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: flask-db
    ports:
     - "5000:5000"

    depends_on:
      - sql-server


networks:
 flask-net:

volumes:
 flask-data:
  