kind: Deployment
apiVersion: apps/v1

metadata:
  name: Flask-Deployment
  namespace: flask-ns
  labels:
    app: Flask-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      name: flask-app
      namespace: flask-ns
      labels:
        app: flask-app

    spec:
      containers:
      - name: flask-container
        image: dharmeshludhani/flask-app:latest
        ports:
        - containerport: 5000

    env:
      - name: MYSQL_HOST
        valueFrom:
          configMapKeyRef:
            name: flask-config
            key: host
      - name: MYSQL_DB
        valueFrom:
          configMapKeyRef:
            name: flask-config
            key: database
      - name: MYSQL_USER
        valueFrom:
          configMapKeyRef:
            name: flask-config
            key: user
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: flask-secret
            key: password
